export const productsData = [
    {
        id: 1,
        name: "Fresas en Éxtasis",
        price: 799,
        category: "bajo",
        description: "Imagina un plato que despierta todos tus sentidos en un solo bocado: las Fresas en Éxtasis. Este exquisito postre es una oda a la frescura y la dulzura de las fresas en su punto máximo de madurez.",
        image: "/public/img/postre_frutilla.jpg",
    },
    {
        id: 2,
        name: "Dona",
        price: 599,
        category: "bajo",
        description: "Esta dona rosada es mucho más que un simple capricho culinario; es un festín para los sentidos que te transporta a un mundo de dulzura y placer. Su aspecto es tan atractivo como su sabor, comenzando por su suave y seductora capa de glaseado rosa que brilla bajo la luz, como un rubí de confitería.",
        image: "/public/img/donut.jpg",
    },
    {
        id: 3,
        name: "Yogurt de frutillas",
        price: 399,
        category: "bajo",
        description: "El yogurt de frutilla es un verdadero regalo para tus sentidos, una delicia que combina la suavidad cremosa del yogurt con la intensidad y la frescura de las frutillas maduras. Es un placer que se presenta en un envase de vidrio, transparente, que permite ver la vibrante paleta de colores que se oculta dentro.",
        image: "/public/img/yogurt.jpg",
    },
    {
        id: 4,
        name: "Tostada dulce",
        price: 499,
        category: "alto",
        description: "Imagina comenzar tu día con una tostada que es más que un simple desayuno, es una experiencia adorable y reconfortante. La tostada con forma de osito es un pequeño tesoro culinario que se presenta ante ti como un abrazo de cariño en la mañana.",
        image: "/public/img/tostadadulce.jpg",
    },
    {
        id: 5,
        name: "Mocha tentador",
        price: 599,
        category: "bajo",
        description: "El mocha es una fusión irresistible de café y chocolate. En una taza se mezcla un espresso con chocolate caliente y se corona con crema batida y virutas de chocolate. Cada sorbo es una indulgencia, con la amargura del café equilibrada por la dulzura del cacao, creando una experiencia verdaderamente decadente.",
        image: "/public/img/coffe6.jpg",
        
    },
    {
        id: 6,
        name: "Cafe Helado",
        price: 399,
        category: "alto",
        description: "El café helado es una delicia fresca y vigorizante. Preparado con café frío o espresso, se mezcla con hielo y a menudo se endulza con jarabe y se corona con crema batida o helado. Es la elección perfecta en un día caluroso, con cada sorbo ofreciendo un equilibrio entre el sabor del café y la refrescante frescura",
        image: "/public/img/coffe4.jpg",
    },
    {
        id: 7,
        name: "Cafe Helado",
        price: 799,
        category: "alto",
        description: "El café helado es una delicia fresca y vigorizante. Preparado con café frío o espresso, se mezcla con hielo y a menudo se endulza con jarabe y se corona con crema batida o helado. Es la elección perfecta en un día caluroso, con cada sorbo ofreciendo un equilibrio entre el sabor del café y la refrescante frescura",
        image: "/public/img/coffe.jpg",    },
    {
        id: 8,
        name: "Cafe Helado",
        price: 599,
        category: "alto",
        description: "El café helado es una delicia fresca y vigorizante. Preparado con café frío o espresso, se mezcla con hielo y a menudo se endulza con jarabe y se corona con crema batida o helado. Es la elección perfecta en un día caluroso, con cada sorbo ofreciendo un equilibrio entre el sabor del café y la refrescante frescura",
        image: "/public/img/coffe5.jpg",
    },
    {
        id: 9,
        name: "Tostada con plata y huevo",
        price: 399,
        category: "bajo",
        description: "El café helado es una delicia fresca y vigorizante. Preparado con café frío o espresso, se mezcla con hielo y a menudo se endulza con jarabe y se corona con crema batida o helado. Es la elección perfecta en un día caluroso, con cada sorbo ofreciendo un equilibrio entre el sabor del café y la refrescante frescura",
        image: "/public/img/tostada.jpg",
    },
    {
        id: 10,
        name: "Latte helado",
        price: 299,
        category: "bajo",
        description: "El café helado es una delicia fresca y vigorizante. Preparado con café frío o espresso, se mezcla con hielo y a menudo se endulza con jarabe y se corona con crema batida o helado. Es la elección perfecta en un día caluroso, con cada sorbo ofreciendo un equilibrio entre el sabor del café y la refrescante frescura",
        image: "/public/img/coffe7.jpg",
    },
    {
        id: 11,
        name: "Cafe Helado Chocolate",
        price: 199,
        category: "bajo",
        description: "El café helado es una delicia fresca y vigorizante. Preparado con café frío o espresso, se mezcla con hielo y a menudo se endulza con jarabe y se corona con crema batida o helado. Es la elección perfecta en un día caluroso, con cada sorbo ofreciendo un equilibrio entre el sabor del café y la refrescante frescura",
        image: "/public/img/coffe11.jpg",
    },
  
]