export const productsData = [
    {
        id: 1,
        name: "Apple iPhone 12",
        price: 799,
        category: "bajo",
        description: "New Apple iPhone 12 (64GB, Blue) [Locked] + Carrier Subscription",
        image: "/public/img/postre_frutilla.jpg",
    },
    {
        id: 2,
        name: "Apple iPhone 11",
        price: 599,
        category: "bajo",
        description: "Apple iPhone 11, 64GB, Black - Fully Unlocked (Renewed)",
        image: "/public/img/donut.jpg",
    },
    {
        id: 3,
        name: "Apple iPhone SE",
        price: 399,
        category: "bajo",
        description: "Apple iPhone SE, 64GB, Black - Fully Unlocked (Renewed Premium)",
        image: "/public/img/cafe3.jpeg",
    },
    {
        id: 4,
        name: "Apple iPhone XR",
        price: 499,
        category: "alto",
        description: "Apple iPhone XR, 64GB, Black - Fully Unlocked (Renewed Premium)",
        image: "/public/img/cafe4.jpeg",
    },
    {
        id: 5,
        name: "Apple iPhone XS",
        price: 599,
        category: "bajo",
        description: "Apple iPhone XS, 64GB, Space Gray - Fully Unlocked (Renewed Premium)",
        image: "/public/img/coffe6.jpg",
        
    },
    {
        id: 6,
        name: "Apple iPhone 8",
        price: 399,
        category: "alto",
        description: "Apple iPhone 8, 64GB, Space Gray - Fully Unlocked (Renewed Premium)",
        image: "/public/img/coffe4.jpg",
    },
    {
        id: 7,
        name: "Samsung Galaxy S20",
        price: 799,
        category: "alto",
        description: "Samsung Galaxy S20 FE 5G | Factory Unlocked Android Cell Phone | 128 GB | US Version Smartphone | Pro-Grade Camera, 30X Space Zoom, Night Mode | Cloud Lavender",
        image: "/public/img/coffe.jpg",    },
    {
        id: 8,
        name: "Samsung Galaxy S10",
        price: 599,
        category: "alto",
        description: "Samsung Galaxy S10+ Plus 128GB+8GB RAM SM-G975F/DS Dual Sim 6.4\" LTE Factory Unlocked Smartphone International Model (Prism Black) (Renewed)",
        image: "/public/img/coffe5.jpg",
    },
    {
        id: 9,
        name: "Samsung Galaxy S9",
        price: 399,
        category: "bajo",
        description: "Samsung Galaxy S9, 64GB, Lilac Purple - Fully Unlocked (Renewed)",
        image: "/public/img/tostada.jpg",
    },
    {
        id: 10,
        name: "Samsung Galaxy S8",
        price: 299,
        category: "bajo",
        description: "Samsung Galaxy S8, 64GB, Midnight Black - Fully Unlocked (Renewed)",
        image: "/public/img/coffe7.jpg",
    },
    {
        id: 11,
        name: "Samsung Galaxy S7",
        price: 199,
        category: "bajo",
        description: "Samsung Galaxy S7 Edge, 32GB, Black - Fully Unlocked (Renewed)",
        image: "/public/img/coffe11.jpg",
    },
  
]